apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "allama.fullname" . }}-ui
  labels:
    {{- include "allama.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "allama.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "allama.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: ui
          image: "{{ .Values.uiImage.repository }}:{{ .Values.uiImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.uiImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- include "allama.env.ui" . | nindent 12 }}
            {{- include "allama.env.secrets.ui" . | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
