[build-system]
requires = ["hatchling >= 1.27.0"]
build-backend = "hatchling.build"

[project]
name = "allama-ee"
description = "Enterprise Edition features for Allama"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "allama_ee/LICENSE.md" }
authors = [{ name = "Allama", email = "founders@allama.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Topic :: Security",
    "Topic :: System :: Systems Administration",
]
dependencies = []
dynamic = ["version"]

[project.urls]
Homepage = "https://allama.com"
Documentation = "https://docs.allama.com/"
Repository = "https://github.com/digitranslab/allama"

[project.entry-points."allama.workflows.git_sync"]
ee_impl = "allama_ee.store.git_sync:sync_repo_workflows"

[project.entry-points."allama.workflows.git_store"]
ee_impl = "allama_ee.store.git_store:GitWorkflowStore"

[tool.hatch.version]
path = "allama_ee/__init__.py"
